name: phredbot

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: beep
      run: |-
        echo "- $(date --utc --iso-8601=seconds)" >>README.md
        git config user.name phredbot
        git config user.email phredbot@gmail.com
        git add --all
        git commit -m "beep"
    - name: boop
      run: git push
